# Generated by Django 4.2.3 on 2023-08-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('codechef', models.CharField(max_length=100)),
                ('codeforces', models.CharField(max_length=100)),
                ('leetcode', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='')),
                ('institute', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('score', models.IntegerField()),
                ('weekly_score', models.IntegerField()),
                ('daily_score', models.IntegerField()),
            ],
        ),
    ]
