# Generated by Django 4.2.3 on 2023-08-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('codechef', models.CharField(default='Not Available', max_length=100)),
                ('codeforces', models.CharField(default='Not Available', max_length=100)),
                ('leetcode', models.CharField(default='Not Available', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
