# Generated by Django 4.2.3 on 2023-09-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_password_profile_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='codechef_token',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='codechef_verified',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='profile',
            name='codeforces_token',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='codeforces_verified',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='profile',
            name='leetcode_token',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='leetcode_verified',
            field=models.BooleanField(default='False'),
        ),
    ]
