# Generated by Django 4.2.3 on 2023-09-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_codechef_token_profile_codechef_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='profile',
            name='institute',
            field=models.CharField(default='@ Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
