# Generated by Django 4.2.3 on 2023-09-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_followers_profile_friends_profile_institute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notification',
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.JSONField(default=dict),
        ),
    ]
